#!/usr/bin/env python3
"""
Build script to generate game_gym.js from game.js
This eliminates code duplication between the human-playable and Gym versions.
"""

import re

def build_gym_version():
    # Read the human-playable version
    with open('game.js', 'r') as f:
        content = f.read()
    
    # Add generated file header
    header = """// ============================================
// GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated from game.js
// Run: python build_gym.py
// ============================================

"""
    
    # Replace the game loop start with a comment
    # Match the exact pattern: requestAnimationFrame(gameLoop);
    gym_content = re.sub(
        r'requestAnimationFrame\(gameLoop\);',
        '// requestAnimationFrame(gameLoop); // Disabled for Gym - controlled via window.step()',
        content
    )
    
    # Write the Gym version
    with open('game_gym.js', 'w') as f:
        f.write(header + gym_content)
    
    print("✓ Built game_gym.js from game.js")
    print("  - Disabled automatic game loop")
    print("  - Game now controlled via window.step() and window.resetGame()")

if __name__ == "__main__":
    build_gym_version()
